name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_env: ['local-library-v1', 'local-library-v2']

    steps:
      - uses: actions/checkout@v4
        with:
          path: ./Celestial-Wayfinder

      # Also checkout esp-utilities repo
      - uses: actions/checkout@v4
        with:
          repository: ammaraskar/blake-esp32-utilities
          path: ./esp32-utilities
      
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        working-directory: ./Celestial-Wayfinder
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        working-directory: ./Celestial-Wayfinder
        run: pio run --environment ${{ matrix.build_env }}
